# Section A: Data Structures & Control Structures
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
3.	Create a set of integers with some duplicate values. Print the set and explain the output.
4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'
7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [1]:
#1. create a list of 5 integers
numbers=[10,20,30,40,50]
print("Original List:", numbers)

Original List: [10, 20, 30, 40, 50]


In [2]:
#append
numbers.append(60)
print("After append:",numbers)

After append: [10, 20, 30, 40, 50, 60]


In [3]:
#extend
numbers.extend([70,80])
print("After extend:", numbers)

After extend: [10, 20, 30, 40, 50, 60, 70, 80]


In [4]:
#insert
numbers.insert(2,25)
print("After insert:", numbers)

After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]


In [5]:
#remove
numbers.remove(30)
print("After remove:", numbers)

After remove: [10, 20, 25, 40, 50, 60, 70, 80]


In [6]:
#pop
numbers.pop()
print("After pop:", numbers)

After pop: [10, 20, 25, 40, 50, 60, 70]


In [7]:
#index
print("Index of 40:", numbers.index(40))

Index of 40: 3


In [8]:
#count
print("Count of 20:", numbers.count(20))

Count of 20: 1


In [9]:
#sort
numbers.sort()
print("After sort:", numbers)

After sort: [10, 20, 25, 40, 50, 60, 70]


In [10]:
#reverse
numbers.reverse()
print("After reverse:", numbers)

After reverse: [70, 60, 50, 40, 25, 20, 10]


In [11]:
#clear
numbers.clear()
print("After clear:", numbers)

After clear: []


In [13]:
#2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
students=("Harshitha", "kavya", "Manasa")
print("original tuple:", students)
#trying to change second name
students[1]="Priya"

original tuple: ('Harshitha', 'kavya', 'Manasa')


TypeError: 'tuple' object does not support item assignment

In [ ]:
#Explanation: tuples are immutable, meaning their values cannot be changed after creation. 
#Attempting to modify them raises a TypeError.

In [14]:
#3.	Create a set of integers with some duplicate values. Print the set and explain the output.
numbers_set={1,2,3,4,4,5,2}
print("set output:", numbers_set)

set output: {1, 2, 3, 4, 5}


In [ ]:
#Explanation:
Sets are automaticallyremove duplicate values,so only unqiue elements are stored.

In [16]:
#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
person={
    "name":"Harshitha",
    "age":22,
    "city":"Bengaluru"
}
#update age
person["age"]=23

#add new key
person["email"]="harshitha@gmail.com"
print("Final Dictionary:",person)

Final Dictionary: {'name': 'Harshitha', 'age': 23, 'city': 'Bengaluru', 'email': 'harshitha@gmail.com'}


In [17]:
#5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age=20
if age>=18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [18]:
#6.	Given a 'marks' variable, print the grade:
#- 90 and above: 'A'
#- 75–89: 'B'
#- 50–74: 'C'
#- Below 50: 'Fail'
marks=78
if marks>=90:
    print("Grade: A")
elif 75<=marks<=89:
    print("Grade: B")
elif 50<=marks<=74:
    print("Grade: C")
else:
    print("Fail")

Grade: B


In [20]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
number=-4
if number>0:
    print("positive number")
    if number%2==0:
        print("It is also even")
    else:
        print("It is odd")
elif number==0:
    print("Number is zero")
else:
    print("Negative number")

Negative number


# Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10
9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [21]:
import numpy as np

In [26]:
#8.	Create:
#- A scalar using np.array(5)
#- A 1D array with values 1 to 5
#- A 2D array (2x3) with values from 10 to 60 in steps of 10
scalar=np.array(5)
print("scalar:",scalar)

#1D array
one_D=np.array([1,2,3,4,5])
print("1D Array:", one_D)

#2D array
two_D=np.array([[10,20,30],
              [40,50,60]])
print("2D array:\n", two_D)


scalar: 5
1D Array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


In [28]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
random_array=np.random.randint(0,101,size=(4,4))
print("Random 4X4 array:\n", random_array)

Random 4X4 array:
 [[55 78 28 82]
 [61 85 32 96]
 [73 78 74 83]
 [20 94 37 30]]


In [32]:
#10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import pandas as pd
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
df = pd.DataFrame(array_2d, columns=["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# Section C: Exploring Pandas
1.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [40]:
data = {
    "Name": ["Asha", "Rahul", "Priya", "Asha", "Kiran", "Meena", "Ravi", "Neha", "Suresh", "Priya"],
    "Age": [25, 28, 22, 25, 30, 27, 26, 24, 29, 22],
    "City": ["Bangalore", "Chennai", "Hyderabad", "Bangalore", "Delhi",
             "Mumbai", "Pune", "Kolkata", "Delhi", "Hyderabad"],
    "Salary": [50000, 60000, None, 50000, 70000, None, 55000, 48000, 65000, None]}
df = pd.DataFrame(data)
#- Use .info(), .describe()
# Info
print(df.info())

# Describe
print(df.describe())

# Select Name and City
print(df[["Name", "City"]])

# Drop City column
df = df.drop(columns=["City"])

# Fill missing Salary with mean
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

# Remove duplicates
df = df.drop_duplicates()

print("\nFinal DataFrame:\n", df)




